package io.github.vovten.eventflow.serialization.msgpack;

import io.github.vovten.eventflow.event.AbstractTraceableEvent;
import io.github.vovten.eventflow.event.Event;
import io.github.vovten.eventflow.serialization.EventSerializationException;
import io.github.vovten.eventflow.serialization.json.JsonEventSerializer;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.Instant;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for MsgPackEventSerializer.
 * @since 1.0.0
 */
@DisplayName("MsgPackEventSerializer Tests")
class MsgPackEventSerializerTest {

    private final MsgPackEventSerializer serializer = new MsgPackEventSerializer();

    @Test
    @DisplayName("Should serialize event to byte array with magic byte")
    void shouldSerializeEventToByteArray() {
        SimpleEvent event = new SimpleEvent("test-id", 42);
        byte[] result = serializer.serialize(event);
        assertNotNull(result);
        assertTrue(result.length > 1);
        assertEquals(0x02, result[0]);
    }

    @Test
    @DisplayName("Should serialize and deserialize event")
    void shouldSerializeAndDeserializeEvent() {
        SimpleEvent original = new SimpleEvent("test-id", 42);
        byte[] data = serializer.serialize(original);
        SimpleEvent deserialized = serializer.deserialize(data, SimpleEvent.class);
        assertEquals("test-id", deserialized.id);
        assertEquals(42, deserialized.value);
    }

    @Test
    @DisplayName("Should return msgpack code")
    void shouldReturnMsgpackCode() {
        assertEquals(0x02, serializer.getCode());
    }

    @Test
    @DisplayName("Should return msgpack name")
    void shouldReturnMsgpackName() {
        assertEquals("msgpack", serializer.getName());
    }

    @Test
    @DisplayName("Should produce smaller output than JSON for simple event")
    void shouldProduceSmallerOutput() {
        SimpleEvent event = new SimpleEvent("test-id", 42);
        byte[] msgpackBytes = serializer.serialize(event);
        byte[] jsonBytes = new JsonEventSerializer().serialize(event);
        assertTrue(msgpackBytes.length < jsonBytes.length,
                "MessagePack (" + msgpackBytes.length + " bytes) should be smaller than JSON (" + jsonBytes.length + " bytes)");
    }

    @Test
    @DisplayName("Should throw exception for null data")
    void shouldThrowExceptionForNullData() {
        assertThrows(EventSerializationException.class, () ->
                serializer.deserialize(null, SimpleEvent.class));
    }

    @Test
    @DisplayName("Should serialize and deserialize AbstractTraceableEvent with all fields")
    void shouldSerializeAndDeserializeAbstractTraceableEvent() {
        UUID fixedUid = UUID.randomUUID();
        UUID fixedProcessId = UUID.fromString("550e8400-e29b-41d4-a716-446655440000");
        Instant fixedInstant = Instant.now().truncatedTo(java.time.temporal.ChronoUnit.MILLIS);

        TraceableTestEvent original = new TraceableTestEvent(fixedUid, fixedProcessId, fixedInstant, "data");

        byte[] data = serializer.serialize(original);
        TraceableTestEvent deserialized = serializer.deserialize(data, TraceableTestEvent.class);

        assertEquals(fixedUid, deserialized.eventId());
        assertEquals(fixedProcessId, deserialized.processId());
        assertEquals(fixedInstant, deserialized.occurredAt());
        assertEquals("data", deserialized.data);
    }

    @Test
    @DisplayName("Should serialize and deserialize event with auto-generated fields")
    void shouldSerializeAndDeserializeEventWithAutoGeneratedFields() {
        TraceableTestEvent original = new TraceableTestEvent("auto-generated");

        byte[] data = serializer.serialize(original);
        TraceableTestEvent deserialized = serializer.deserialize(data, TraceableTestEvent.class);

        assertNotNull(deserialized.eventId());
        assertNull(deserialized.processId());
        assertNotNull(deserialized.occurredAt());
        assertEquals("auto-generated", deserialized.data);
    }

    @Test
    @DisplayName("Should preserve event type after serialization")
    void shouldPreserveEventTypeAfterSerialization() {
        TraceableTestEvent original = new TraceableTestEvent("type-test");
        byte[] data = serializer.serialize(original);
        TraceableTestEvent deserialized = serializer.deserialize(data, TraceableTestEvent.class);
        assertEquals(original.type(), deserialized.type());
    }

    @Test
    @DisplayName("Should handle complex event with nested objects")
    void shouldHandleComplexEventWithNestedObjects() {
        UUID processId = UUID.fromString("550e8400-e29b-41d4-a716-446655440001");
        ComplexTraceableEvent original = new ComplexTraceableEvent(
                UUID.randomUUID(),
                processId,
                Instant.now().truncatedTo(java.time.temporal.ChronoUnit.MILLIS),
                "complex-data",
                42,
                new NestedObject("nested-value", 100)
        );

        byte[] data = serializer.serialize(original);
        ComplexTraceableEvent deserialized = serializer.deserialize(data, ComplexTraceableEvent.class);

        assertEquals(original.eventId(), deserialized.eventId());
        assertEquals(original.processId(), deserialized.processId());
        assertNotNull(deserialized.occurredAt());
        assertEquals("complex-data", deserialized.data);
        assertEquals(42, deserialized.value);
        assertEquals("nested-value", deserialized.nested.name);
        assertEquals(100, deserialized.nested.count);
    }

    static class SimpleEvent extends AbstractTraceableEvent {

        public String id;
        public int value;

        SimpleEvent() {
            super();
        }

        SimpleEvent(String id, int value) {
            super();
            this.id = id;
            this.value = value;
        }

        @Override
        public Class<? extends Event> type() {
            return SimpleEvent.class;
        }
    }

    static class TraceableTestEvent extends AbstractTraceableEvent {

        public String data;

        TraceableTestEvent() {
            super();
        }

        TraceableTestEvent(String data) {
            super();
            this.data = data;
        }

        TraceableTestEvent(UUID uid, UUID processId, Instant occurredAt, String data) {
            super(uid, processId, occurredAt);
            this.data = data;
        }

        @Override
        public Class<? extends Event> type() {
            return TraceableTestEvent.class;
        }
    }

    static class ComplexTraceableEvent extends AbstractTraceableEvent {

        public String data;
        public int value;
        public NestedObject nested;

        ComplexTraceableEvent() {
            super();
        }

        ComplexTraceableEvent(UUID uid, UUID processId, Instant occurredAt, String data, int value, NestedObject nested) {
            super(uid, processId, occurredAt);
            this.data = data;
            this.value = value;
            this.nested = nested;
        }

        @Override
        public Class<? extends Event> type() {
            return ComplexTraceableEvent.class;
        }
    }

    static class NestedObject {

        public String name;
        public int count;

        NestedObject() {
        }

        NestedObject(String name, int count) {
            this.name = name;
            this.count = count;
        }
    }
}