spring.kafka.bootstrap-servers=localhost:9092

event.dispatcher.thread.pool.size=10
event.listener.scan.package=com.github.vovten.eventflow

# Enables publishing and consumption of events by this application within the internal bus
event.internal.enabled=true

# Enables consumption of events from the external bus by each service instance (pods)
event.replicas.dispatcher.enabled=false

# Enables publishing of this application's events to the external bus
event.external.publisher.enabled=false

# Defines the topic through which this application publishes events to the external bus
event.service.topic=eventflow.io-events

# Enables consumption of events distributed by other applications via the external bus
event.external.dispatcher.enabled=false

# Defines the topics from which this application consumes events distributed by other applications via the external bus
# Example: event.external.dispatcher.topics=eventflow.io-prep-events,eventflow.docs-events
event.external.dispatcher.topics=eventflow.io-prep-events

# Enables event publishing only after transaction commit
event.transactional.publishing.enabled=true
