package io.github.vovten.eventflow.event;

import io.github.vovten.eventflow.channel.ExternalEventChannel;
import io.github.vovten.eventflow.channel.EventChannel;
import io.github.vovten.eventflow.channel.InternalEventChannel;
import io.github.vovten.eventflow.publisher.ChannelEventPublisher;
import io.github.vovten.eventflow.publisher.EventPublisher;
import io.github.vovten.eventflow.transport.OutTransport;
import io.github.vovten.eventflow.transport.outgoing.LocalQueueOutTransport;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.BlockingDeque;
import java.util.concurrent.LinkedBlockingDeque;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * @since 1.1.0
 */
@DisplayName("DefaultEventBuilder Tests")
class DefaultEventBuilderTest {

    @Test
    @DisplayName("Should create builder and publish with auto-generated metadata")
    void shouldCreateBuilderAndPublishWithAutoGeneratedMetadata() {
        BlockingDeque<Event> queue = new LinkedBlockingDeque<>();
        OutTransport transport = new LocalQueueOutTransport(queue);
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new ChannelEventPublisher(List.of(channel));

        TestPayload payload = new TestPayload("test-123");
        new DefaultEventBuilder<>(publisher, payload).publish().join();
        assertThat(payload).isNotNull();
    }

    @Test
    @DisplayName("Should set custom processId")
    void shouldSetCustomProcessId() {
        BlockingDeque<Event> queue = new LinkedBlockingDeque<>();
        OutTransport transport = new LocalQueueOutTransport(queue);
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new ChannelEventPublisher(List.of(channel));

        UUID customProcessId = UUID.fromString("550e8400-e29b-41d4-a716-446655440000");
        TestPayload payload = new TestPayload("test");
        new DefaultEventBuilder<>(publisher, payload)
                .withProcessId(customProcessId)
                .publish()
                .join();

        Envelope<?> capturedEnvelope = (Envelope<?>) queue.poll();
        assertThat(capturedEnvelope).isNotNull();
        assertThat(capturedEnvelope.processId()).isEqualTo(customProcessId);
    }

    @Test
    @DisplayName("Should set custom occurredAt")
    void shouldSetCustomOccurredAt() {
        BlockingDeque<Event> queue = new LinkedBlockingDeque<>();
        OutTransport transport = new LocalQueueOutTransport(queue);
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new ChannelEventPublisher(List.of(channel));

        Instant customTime = Instant.parse("2025-01-15T10:30:00Z");
        TestPayload payload = new TestPayload("test");
        new DefaultEventBuilder<>(publisher, payload)
                .withOccurredAt(customTime)
                .publish()
                .join();

        Envelope<?> capturedEnvelope = (Envelope<?>) queue.poll();
        assertThat(capturedEnvelope).isNotNull();
        assertThat(capturedEnvelope.occurredAt()).isEqualTo(customTime);
    }

    @Test
    @DisplayName("Should add single metadata entry")
    void shouldAddSingleMetadataEntry() {
        BlockingDeque<Event> queue = new LinkedBlockingDeque<>();
        OutTransport transport = new LocalQueueOutTransport(queue);
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new ChannelEventPublisher(List.of(channel));

        TestPayload payload = new TestPayload("test");
        new DefaultEventBuilder<>(publisher, payload)
                .withMetadata("source", "web-api")
                .publish()
                .join();

        Envelope<?> capturedEnvelope = (Envelope<?>) queue.poll();
        assertThat(capturedEnvelope).isNotNull();
        assertThat(capturedEnvelope.metadata()).containsEntry("source", "web-api");
    }

    @Test
    @DisplayName("Should add multiple metadata entries")
    void shouldAddMultipleMetadataEntries() {
        BlockingDeque<Event> queue = new LinkedBlockingDeque<>();
        OutTransport transport = new LocalQueueOutTransport(queue);
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new ChannelEventPublisher(List.of(channel));

        TestPayload payload = new TestPayload("test");
        Map<String, String> metadata = Map.of("source", "api", "version", "1.0");
        new DefaultEventBuilder<>(publisher, payload)
                .withMetadata(metadata)
                .publish()
                .join();

        Envelope<?> capturedEnvelope = (Envelope<?>) queue.poll();
        assertThat(capturedEnvelope).isNotNull();
        assertThat(capturedEnvelope.metadata())
                .containsEntry("source", "api")
                .containsEntry("version", "1.0");
    }

    @Test
    @DisplayName("Should chain multiple with methods")
    void shouldChainMultipleWithMethods() {
        BlockingDeque<Event> queue = new LinkedBlockingDeque<>();
        OutTransport transport = new LocalQueueOutTransport(queue);
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new ChannelEventPublisher(List.of(channel));

        UUID customProcessId = UUID.fromString("550e8400-e29b-41d4-a716-446655440001");
        Instant customTime = Instant.parse("2025-02-20T08:00:00Z");
        TestPayload payload = new TestPayload("test");
        new DefaultEventBuilder<>(publisher, payload)
                .withProcessId(customProcessId)
                .withOccurredAt(customTime)
                .withMetadata("key1", "value1")
                .withMetadata("key2", "value2")
                .publish()
                .join();

        Envelope<?> capturedEnvelope = (Envelope<?>) queue.poll();
        assertThat(capturedEnvelope).isNotNull();
        assertThat(capturedEnvelope.eventId()).isNotNull();
        assertThat(capturedEnvelope.processId()).isEqualTo(customProcessId);
        assertThat(capturedEnvelope.occurredAt()).isEqualTo(customTime);
        assertThat(capturedEnvelope.metadata())
                .containsEntry("key1", "value1")
                .containsEntry("key2", "value2");
    }

    @Test
    @DisplayName("Should include payload type in metadata")
    void shouldIncludePayloadTypeInMetadata() {
        BlockingDeque<Event> queue = new LinkedBlockingDeque<>();
        OutTransport transport = new LocalQueueOutTransport(queue);
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new ChannelEventPublisher(List.of(channel));

        TestPayload payload = new TestPayload("test");
        new DefaultEventBuilder<>(publisher, payload).publish().join();

        Envelope<?> capturedEnvelope = (Envelope<?>) queue.poll();
        assertThat(capturedEnvelope).isNotNull();
        assertThat(capturedEnvelope.payload()).isEqualTo(payload);
    }

    @Test
    @DisplayName("Should set target channels via withChannels")
    void shouldSetTargetChannelsViaWithChannels() {
        BlockingDeque<Event> queue = new LinkedBlockingDeque<>();
        OutTransport transport = new LocalQueueOutTransport(queue);
        EventChannel internalChannel = new InternalEventChannel(transport);
        EventChannel externalChannel = new ExternalEventChannel(List.of(transport));
        EventPublisher publisher = new ChannelEventPublisher(List.of(internalChannel, externalChannel));

        TestPayload payload = new TestPayload("test");
        new DefaultEventBuilder<>(publisher, payload)
                .withChannel(ExternalEventChannel.class)
                .publish()
                .join();

        Envelope<?> capturedEnvelope = (Envelope<?>) queue.poll();
        assertThat(capturedEnvelope).isNotNull();
        assertThat(capturedEnvelope.channels()).containsExactly(ExternalEventChannel.class);
    }

    @Test
    @DisplayName("Should support multiple channels via withChannels")
    void shouldSupportMultipleChannelsViaWithChannels() {
        BlockingDeque<Event> queue = new LinkedBlockingDeque<>();
        OutTransport transport = new LocalQueueOutTransport(queue);
        EventChannel internalChannel = new InternalEventChannel(transport);
        EventChannel externalChannel = new ExternalEventChannel(List.of(transport));
        EventPublisher publisher = new ChannelEventPublisher(List.of(internalChannel, externalChannel));

        TestPayload payload = new TestPayload("test");
        new DefaultEventBuilder<>(publisher, payload)
                .withChannels(InternalEventChannel.class, ExternalEventChannel.class)
                .publish()
                .join();

        Envelope<?> capturedEnvelope = (Envelope<?>) queue.poll();
        assertThat(capturedEnvelope).isNotNull();
        assertThat(capturedEnvelope.channels()).containsExactly(InternalEventChannel.class, ExternalEventChannel.class);
    }

    @Test
    @DisplayName("Should support three channels via withChannels")
    void shouldSupportThreeChannelsViaWithChannels() {
        BlockingDeque<Event> queue = new LinkedBlockingDeque<>();
        OutTransport transport = new LocalQueueOutTransport(queue);
        EventChannel internalChannel = new InternalEventChannel(transport);
        EventChannel externalChannel = new ExternalEventChannel(List.of(transport));
        EventPublisher publisher = new ChannelEventPublisher(List.of(internalChannel, externalChannel));

        TestPayload payload = new TestPayload("test");
        new DefaultEventBuilder<>(publisher, payload)
                .withChannels(InternalEventChannel.class, ExternalEventChannel.class, InternalEventChannel.class)
                .publish()
                .join();

        Envelope<?> capturedEnvelope = (Envelope<?>) queue.poll();
        assertThat(capturedEnvelope).isNotNull();
        assertThat(capturedEnvelope.channels()).containsExactly(InternalEventChannel.class, ExternalEventChannel.class, InternalEventChannel.class);
    }

    @Test
    @DisplayName("Should support varargs channels via withChannels")
    void shouldSupportVarargsChannelsViaWithChannels() {
        BlockingDeque<Event> queue = new LinkedBlockingDeque<>();
        OutTransport transport = new LocalQueueOutTransport(queue);
        EventChannel internalChannel = new InternalEventChannel(transport);
        EventChannel externalChannel = new ExternalEventChannel(List.of(transport));
        EventPublisher publisher = new ChannelEventPublisher(List.of(internalChannel, externalChannel));

        TestPayload payload = new TestPayload("test");
        new DefaultEventBuilder<>(publisher, payload)
                .withChannels(List.of(InternalEventChannel.class, ExternalEventChannel.class))
                .publish()
                .join();

        Envelope<?> capturedEnvelope = (Envelope<?>) queue.poll();
        assertThat(capturedEnvelope).isNotNull();
        assertThat(capturedEnvelope.channels()).containsExactly(InternalEventChannel.class, ExternalEventChannel.class);
    }

    @Test
    @DisplayName("Should throw exception when withChannels called with null list")
    void shouldThrowExceptionWhenWithChannelsCalledWithNullList() {
        BlockingDeque<Event> queue = new LinkedBlockingDeque<>();
        OutTransport transport = new LocalQueueOutTransport(queue);
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new ChannelEventPublisher(List.of(channel));
        TestPayload payload = new TestPayload("test");
        assertThatThrownBy(() -> new DefaultEventBuilder<>(publisher, payload)
                .withChannels((List<Class<? extends EventChannel>>) null))
                .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    @DisplayName("Should throw exception when withChannels called with empty list")
    void shouldThrowExceptionWhenWithChannelsCalledWithEmptyList() {
        BlockingDeque<Event> queue = new LinkedBlockingDeque<>();
        OutTransport transport = new LocalQueueOutTransport(queue);
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new ChannelEventPublisher(List.of(channel));
        TestPayload payload = new TestPayload("test");
        assertThatThrownBy(() -> new DefaultEventBuilder<>(publisher, payload)
                .withChannels(List.of()))
                .isInstanceOf(IllegalArgumentException.class);
    }

    record TestPayload(String value) {}
}