package io.github.vovten.eventflow.event;

import io.github.vovten.eventflow.channel.ExternalEventChannel;
import io.github.vovten.eventflow.channel.EventChannel;
import io.github.vovten.eventflow.channel.InternalEventChannel;
import io.github.vovten.eventflow.publisher.EventPublisher;
import io.github.vovten.eventflow.transport.OutTransport;
import io.github.vovten.eventflow.transport.SendResult;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.atomic.AtomicReference;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

@DisplayName("DefaultEventBuilder Tests")
class DefaultEventBuilderTest {

    @Test
    @DisplayName("Should create builder and publish with auto-generated metadata")
    void shouldCreateBuilderAndPublishWithAutoGeneratedMetadata() {
        OutTransport transport = mock(OutTransport.class);
        when(transport.send(any())).thenReturn(CompletableFuture.completedFuture(SendResult.success("dest")));
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new io.github.vovten.eventflow.publisher.ChannelEventPublisher(List.of(channel));

        TestPayload payload = new TestPayload("test-123");
        new DefaultEventBuilder<>(publisher, payload).publish().join();

        assertThat(payload).isNotNull();
    }

    @Test
    @DisplayName("Should set custom eventId")
    void shouldSetCustomEventId() {
        OutTransport transport = mock(OutTransport.class);
        AtomicReference<Envelope<?>> capturedEnvelope = new AtomicReference<>();
        when(transport.send(any())).thenAnswer(invocation -> {
            capturedEnvelope.set((Envelope<?>) invocation.getArgument(0));
            return CompletableFuture.completedFuture(SendResult.success("dest"));
        });
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new io.github.vovten.eventflow.publisher.ChannelEventPublisher(List.of(channel));

        UUID customId = UUID.randomUUID();
        TestPayload payload = new TestPayload("test");
        new DefaultEventBuilder<>(publisher, payload)
                .withEventId(customId)
                .publish()
                .join();

        assertThat(capturedEnvelope.get()).isNotNull();
        assertThat(capturedEnvelope.get().eventId()).isEqualTo(customId);
    }

    @Test
    @DisplayName("Should set custom traceId")
    void shouldSetCustomTraceId() {
        OutTransport transport = mock(OutTransport.class);
        AtomicReference<Envelope<?>> capturedEnvelope = new AtomicReference<>();
        when(transport.send(any())).thenAnswer(invocation -> {
            capturedEnvelope.set((Envelope<?>) invocation.getArgument(0));
            return CompletableFuture.completedFuture(SendResult.success("dest"));
        });
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new io.github.vovten.eventflow.publisher.ChannelEventPublisher(List.of(channel));

        String customTraceId = "550e8400-e29b-41d4-a716-446655440000";
        TestPayload payload = new TestPayload("test");
        new DefaultEventBuilder<>(publisher, payload)
                .withTraceId(customTraceId)
                .publish()
                .join();

        assertThat(capturedEnvelope.get()).isNotNull();
        assertThat(capturedEnvelope.get().traceId()).isEqualTo(UUID.nameUUIDFromBytes(customTraceId.getBytes()));
    }

    @Test
    @DisplayName("Should set custom occurredAt")
    void shouldSetCustomOccurredAt() {
        OutTransport transport = mock(OutTransport.class);
        AtomicReference<Envelope<?>> capturedEnvelope = new AtomicReference<>();
        when(transport.send(any())).thenAnswer(invocation -> {
            capturedEnvelope.set((Envelope<?>) invocation.getArgument(0));
            return CompletableFuture.completedFuture(SendResult.success("dest"));
        });
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new io.github.vovten.eventflow.publisher.ChannelEventPublisher(List.of(channel));

        Instant customTime = Instant.parse("2025-01-15T10:30:00Z");
        TestPayload payload = new TestPayload("test");
        new DefaultEventBuilder<>(publisher, payload)
                .withOccurredAt(customTime)
                .publish()
                .join();

        assertThat(capturedEnvelope.get()).isNotNull();
        assertThat(capturedEnvelope.get().occurredAt()).isEqualTo(customTime);
    }

    @Test
    @DisplayName("Should add single metadata entry")
    void shouldAddSingleMetadataEntry() {
        OutTransport transport = mock(OutTransport.class);
        AtomicReference<Envelope<?>> capturedEnvelope = new AtomicReference<>();
        when(transport.send(any())).thenAnswer(invocation -> {
            capturedEnvelope.set((Envelope<?>) invocation.getArgument(0));
            return CompletableFuture.completedFuture(SendResult.success("dest"));
        });
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new io.github.vovten.eventflow.publisher.ChannelEventPublisher(List.of(channel));

        TestPayload payload = new TestPayload("test");
        new DefaultEventBuilder<>(publisher, payload)
                .withMetadata("source", "web-api")
                .publish()
                .join();

        assertThat(capturedEnvelope.get()).isNotNull();
        assertThat(capturedEnvelope.get().metadata()).containsEntry("source", "web-api");
    }

    @Test
    @DisplayName("Should add multiple metadata entries")
    void shouldAddMultipleMetadataEntries() {
        OutTransport transport = mock(OutTransport.class);
        AtomicReference<Envelope<?>> capturedEnvelope = new AtomicReference<>();
        when(transport.send(any())).thenAnswer(invocation -> {
            capturedEnvelope.set((Envelope<?>) invocation.getArgument(0));
            return CompletableFuture.completedFuture(SendResult.success("dest"));
        });
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new io.github.vovten.eventflow.publisher.ChannelEventPublisher(List.of(channel));

        TestPayload payload = new TestPayload("test");
        Map<String, String> metadata = Map.of("source", "api", "version", "1.0");
        new DefaultEventBuilder<>(publisher, payload)
                .withMetadata(metadata)
                .publish()
                .join();

        assertThat(capturedEnvelope.get()).isNotNull();
        assertThat(capturedEnvelope.get().metadata())
                .containsEntry("source", "api")
                .containsEntry("version", "1.0");
    }

    @Test
    @DisplayName("Should chain multiple with methods")
    void shouldChainMultipleWithMethods() {
        OutTransport transport = mock(OutTransport.class);
        AtomicReference<Envelope<?>> capturedEnvelope = new AtomicReference<>();
        when(transport.send(any())).thenAnswer(invocation -> {
            capturedEnvelope.set((Envelope<?>) invocation.getArgument(0));
            return CompletableFuture.completedFuture(SendResult.success("dest"));
        });
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new io.github.vovten.eventflow.publisher.ChannelEventPublisher(List.of(channel));

        UUID customId = UUID.randomUUID();
        UUID customTraceId = UUID.fromString("550e8400-e29b-41d4-a716-446655440001");
        Instant customTime = Instant.parse("2025-02-20T08:00:00Z");
        TestPayload payload = new TestPayload("test");
        new DefaultEventBuilder<>(publisher, payload)
                .withEventId(customId)
                .withTraceId(customTraceId)
                .withOccurredAt(customTime)
                .withMetadata("key1", "value1")
                .withMetadata("key2", "value2")
                .publish()
                .join();

        assertThat(capturedEnvelope.get()).isNotNull();
        assertThat(capturedEnvelope.get().eventId()).isEqualTo(customId);
        assertThat(capturedEnvelope.get().traceId()).isEqualTo(customTraceId);
        assertThat(capturedEnvelope.get().occurredAt()).isEqualTo(customTime);
        assertThat(capturedEnvelope.get().metadata())
                .containsEntry("key1", "value1")
                .containsEntry("key2", "value2");
    }

    @Test
    @DisplayName("Should include payload type in metadata")
    void shouldIncludePayloadTypeInMetadata() {
        OutTransport transport = mock(OutTransport.class);
        AtomicReference<Envelope<?>> capturedEnvelope = new AtomicReference<>();
        when(transport.send(any())).thenAnswer(invocation -> {
            capturedEnvelope.set((Envelope<?>) invocation.getArgument(0));
            return CompletableFuture.completedFuture(SendResult.success("dest"));
        });
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new io.github.vovten.eventflow.publisher.ChannelEventPublisher(List.of(channel));

        TestPayload payload = new TestPayload("test");
        new DefaultEventBuilder<>(publisher, payload).publish().join();

        assertThat(capturedEnvelope.get()).isNotNull();
        assertThat(capturedEnvelope.get().getPayloadType()).isEqualTo(TestPayload.class.getName());
    }

    @Test
    @DisplayName("Should parse string eventId")
    void shouldParseStringEventId() {
        OutTransport transport = mock(OutTransport.class);
        AtomicReference<Envelope<?>> capturedEnvelope = new AtomicReference<>();
        when(transport.send(any())).thenAnswer(invocation -> {
            capturedEnvelope.set((Envelope<?>) invocation.getArgument(0));
            return CompletableFuture.completedFuture(SendResult.success("dest"));
        });
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new io.github.vovten.eventflow.publisher.ChannelEventPublisher(List.of(channel));

        UUID expectedId = UUID.randomUUID();
        TestPayload payload = new TestPayload("test");
        new DefaultEventBuilder<>(publisher, payload)
                .withEventId(expectedId.toString())
                .publish()
                .join();

        assertThat(capturedEnvelope.get()).isNotNull();
        assertThat(capturedEnvelope.get().eventId()).isEqualTo(expectedId);
    }

    @Test
    @DisplayName("Should set target channels via withChannels")
    void shouldSetTargetChannelsViaWithChannels() {
        OutTransport transport = mock(OutTransport.class);
        AtomicReference<Envelope<?>> capturedEnvelope = new AtomicReference<>();
        when(transport.send(any())).thenAnswer(invocation -> {
            capturedEnvelope.set((Envelope<?>) invocation.getArgument(0));
            return CompletableFuture.completedFuture(SendResult.success("dest"));
        });
        EventChannel internalChannel = new InternalEventChannel(transport);
        EventChannel externalChannel = new ExternalEventChannel(List.of(transport));
        EventPublisher publisher = new io.github.vovten.eventflow.publisher.ChannelEventPublisher(List.of(internalChannel, externalChannel));

        TestPayload payload = new TestPayload("test");
        new DefaultEventBuilder<>(publisher, payload)
                .withChannels(ExternalEventChannel.class)
                .publish()
                .join();

        assertThat(capturedEnvelope.get()).isNotNull();
        assertThat(capturedEnvelope.get().channels()).containsExactly(ExternalEventChannel.class);
    }

    @Test
    @DisplayName("Should support multiple channels via withChannels")
    void shouldSupportMultipleChannelsViaWithChannels() {
        OutTransport transport = mock(OutTransport.class);
        AtomicReference<Envelope<?>> capturedEnvelope = new AtomicReference<>();
        when(transport.send(any())).thenAnswer(invocation -> {
            capturedEnvelope.set((Envelope<?>) invocation.getArgument(0));
            return CompletableFuture.completedFuture(SendResult.success("dest"));
        });
        EventChannel internalChannel = new InternalEventChannel(transport);
        EventChannel externalChannel = new ExternalEventChannel(List.of(transport));
        EventPublisher publisher = new io.github.vovten.eventflow.publisher.ChannelEventPublisher(List.of(internalChannel, externalChannel));

        TestPayload payload = new TestPayload("test");
        new DefaultEventBuilder<>(publisher, payload)
                .withChannels(InternalEventChannel.class, ExternalEventChannel.class)
                .publish()
                .join();

        assertThat(capturedEnvelope.get()).isNotNull();
        assertThat(capturedEnvelope.get().channels()).containsExactly(InternalEventChannel.class, ExternalEventChannel.class);
    }

    @Test
    @DisplayName("Should throw exception when withChannels called with null")
    void shouldThrowExceptionWhenWithChannelsCalledWithNull() {
        OutTransport transport = mock(OutTransport.class);
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new io.github.vovten.eventflow.publisher.ChannelEventPublisher(List.of(channel));

        TestPayload payload = new TestPayload("test");

        assertThatThrownBy(() -> new DefaultEventBuilder<>(publisher, payload)
                .withChannels((Class<? extends EventChannel>[]) null))
                .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    @DisplayName("Should throw exception when withChannels called with empty array")
    void shouldThrowExceptionWhenWithChannelsCalledWithEmptyArray() {
        OutTransport transport = mock(OutTransport.class);
        EventChannel channel = new InternalEventChannel(transport);
        EventPublisher publisher = new io.github.vovten.eventflow.publisher.ChannelEventPublisher(List.of(channel));

        TestPayload payload = new TestPayload("test");

        assertThatThrownBy(() -> new DefaultEventBuilder<>(publisher, payload)
                .withChannels(new Class[0]))
                .isInstanceOf(IllegalArgumentException.class);
    }

    record TestPayload(String value) {}
}
